//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public Articulo()
        {
            this.PedidoVentaDetalles = new HashSet<PedidoVentaDetalle>();
        }
    
        public int Id { get; set; }
        public string Denominacion { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public int RubroID { get; set; }
    
        public virtual Rubro Rubro { get; set; }
        public virtual ICollection<PedidoVentaDetalle> PedidoVentaDetalles { get; set; }
    }
}
