//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.PedidoVentas = new HashSet<PedidoVenta>();
        }
    
        public int Id { get; set; }
        public string RazonSocial { get; set; }
        public string Cuit { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> DomicilioID { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual ICollection<PedidoVenta> PedidoVentas { get; set; }
    }
}
