//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public Domicilio()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int ID { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Localidad { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
