//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrdenesDBConnection : DbContext
    {
        public OrdenesDBConnection()
            : base("name=OrdenesDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulo> Articuloes { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Domicilio> Domicilios { get; set; }
        public DbSet<PedidoVenta> PedidoVentas { get; set; }
        public DbSet<PedidoVentaDetalle> PedidoVentaDetalles { get; set; }
        public DbSet<Rubro> Rubroes { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
