//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoVentaDetalle
    {
        public int id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> PorcentajeDescuento { get; set; }
        public int PedidoVentaID { get; set; }
        public int ArticuloID { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual PedidoVenta PedidoVenta { get; set; }
    }
}
