//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoVenta
    {
        public PedidoVenta()
        {
            this.PedidoVentaDetalles = new HashSet<PedidoVentaDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
        public Nullable<decimal> GastosEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<long> NroPedido { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public int ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<PedidoVentaDetalle> PedidoVentaDetalles { get; set; }
    }
}
