//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Articuloes = new HashSet<Articulo>();
            this.Rubro1 = new HashSet<Rubro>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Denominacion { get; set; }
        public Nullable<int> RubroPadreId { get; set; }
    
        public virtual ICollection<Articulo> Articuloes { get; set; }
        public virtual ICollection<Rubro> Rubro1 { get; set; }
        public virtual Rubro Rubro2 { get; set; }
    }
}
